-- return {}
-- return {
-- 'SvenRehm/njem.nvim',
-- config = function()
--   vim.cmd [[colorscheme tokyonight-njem]]
-- end,
--   'jesseleite/nvim-noirbuddy',
--   dependencies = {
--     { 'tjdevries/colorbuddy.nvim', branch = 'dev' },
--   },
--   lazy = false,
--   priority = 1000,
--   opts = {
--     preset = 'miami-nights',
--   },
-- }
return {
  -- 'folke/tokyonight.nvim',
  -- config = function()
  --   vim.cmd [[colorscheme tokyonight-storm]]
  -- end,
  -- lazy = false,
  -- priority = 1000,
  -- opts = {
  --   style = 'storm',
  --   -- preset = 'miami-nights',
  -- },

  -- sidebars = { 'qf', 'vista_kind', 'terminal', 'packer' },
  -- Change the "hint" color to the "orange" color, and make the "error" color bright red
}
