-- return {
-- 'SvenRehm/njem.nvim',
-- config = function()
--   vim.cmd [[colorscheme tokyonight-njem]]
-- end,
--   'jesseleite/nvim-noirbuddy',
--   dependencies = {
--     { 'tjdevries/colorbuddy.nvim', branch = 'dev' },
--   },
--   lazy = false,
--   priority = 1000,
--   opts = {
--     preset = 'miami-nights',
--   },
-- }
--
-- return {
--   {
--     'folke/tokyonight.nvim',
--     -- priority = 1000,
--     -- init = function()
--     --   vim.cmd.colorscheme 'tokyonight-storm'
--     -- end,
--     opts = {
--       terminal_colors = true,
--       styles = {
--         comments = { italic = false },
--         keywords = { italic = false },
--         functions = {},
--         variables = {},
--         sidebars = 'dark', -- style for sidebars, see below
--         floats = 'dark', -- style for floating windows
--       },
--       on_colors = function(colors)
--         colors.bg = '#101010'
--       end,
--     },
--   },
--   {
--     'ramojus/mellifluous.nvim',
--     -- priority = 1000,
--     -- version = "v0.*", -- uncomment for stable config (some features might be missed if/when v1 comes out)
--     config = function()
--       require('mellifluous').setup {
--         mellifluous = {
--           dark = {
--             main_keywords = '#e0e066',
--           },
--         },
--       } -- optional, see configuration section.
--
--       -- vim.cmd 'colorscheme mellifluous'
--     end,
--   },
--   {
--     'aktersnurra/no-clown-fiesta.nvim',
--     config = function()
--       require('no-clown-fiesta').setup {
--         transparent = true, -- Enable this to disable the bg color
--         styles = {
--           comments = {},
--           functions = {},
--           keywords = {},
--           lsp = {},
--           match_paren = { underline = true },
--           type = { bold = true },
--           variables = {},
--         },
--       }
--       vim.cmd [[colorscheme no-clown-fiesta]]
--     end,
--   },
-- }

-- return {
--   'jesseleite/nvim-noirbuddy',
--   dependencies = {
--     { 'tjdevries/colorbuddy.nvim' },
--   },
--   lazy = false,
--   priority = 1000,
--   opts = {},
--   config = function()
--     require('noirbuddy').setup {
--       preset = 'minimal',
--       colors = {
--         primary = '#FEBA68',
--         secondary = '#db73de',
--         background = '#1f1f1f',
--
--         diff_add = '#f5f5f5',
--         diff_change = '#737373',
--         diff_delete = '#EC0034',
--       },
--     }
--
--     local colorbuddy = require 'colorbuddy'
--     local Color = colorbuddy.Color
--     local colors2 = colorbuddy.colors
--     local Group = colorbuddy.Group
--     local groups = colorbuddy.groups
--     local styles = colorbuddy.styles
--     Group.new('CursorLineNr', colors2.primary, colors2.background)
--     -- Group.new('GitSignsAdd', colors2.diff_add, colors2.background)
--     -- Group.new('GitSignsChange', colors2.diff_change, colors2.background)
--
--     require('catppuccin').setup {}
--     local colors = require('catppuccin.palettes').get_palette()
--
--     local TelescopeColor = {
--       TelescopeMatching = { fg = colors.flamingo },
--       TelescopeSelection = { fg = colors.text, bg = colors.surface0, bold = true },
--
--       TelescopePromptPrefix = { bg = colors.surface0 },
--       TelescopePromptNormal = { bg = colors.surface0 },
--       TelescopeResultsNormal = { bg = colors.mantle },
--       TelescopePreviewNormal = { bg = colors.mantle },
--       TelescopePromptBorder = { bg = colors.surface0, fg = colors.surface0 },
--       TelescopeResultsBorder = { bg = colors.mantle, fg = colors.mantle },
--       TelescopePreviewBorder = { bg = colors.mantle, fg = colors.mantle },
--       TelescopePromptTitle = { bg = colors.pink, fg = colors.mantle },
--       TelescopeResultsTitle = { fg = colors.mantle },
--       TelescopePreviewTitle = { bg = colors.green, fg = colors.mantle },
--     }
--     for hl, col in pairs(TelescopeColor) do
--       vim.api.nvim_set_hl(0, hl, col)
--     end
--   end,
-- }
return {}
