-- local colors = {
--   blue = "#80a0ff",
--   cyan = "#79dac8",
--   black = "#080808",
--   white = "#c6c6c6",
--   red = "#ff5189",
--   violet = "#d183e8",
--   grey = "#303030",
-- }
--
-- local bubbles_theme = {
--   normal = {
--     a = { fg = colors.white, bg = colors.grey },
--     b = { fg = colors.white, bg = colors.grey },
--     c = { fg = colors.white },
--   },
--
--   insert = { a = { fg = colors.black, bg = colors.blue } },
--   visual = { a = { fg = colors.black, bg = colors.cyan } },
--   replace = { a = { fg = colors.black, bg = colors.red } },
--
--   inactive = {
--     a = { fg = colors.white, bg = colors.black },
--     b = { fg = colors.white, bg = colors.black },
--     c = { fg = colors.white },
--   },
-- }
--
-- return {
--   "nvim-lualine/lualine.nvim",
--   event = "VeryLazy",
--   opts = function()
--     return {
--       require("lualine").setup({
--         options = {
--           theme = bubbles_theme,
--           component_separators = "▎",
--           section_separators = "",
--         },
--         sections = {
--           lualine_a = { { "mode", separator = "", left_padding = 2, right_padding = 2 } },
--           lualine_b = { "branch", "filename" },
--           lualine_c = {
--             "%=", --[[ add your center compoentnts here in place of this comment ]]
--           },
--           lualine_x = {},
--           lualine_y = { "progress" },
--           lualine_z = {
--             { "filetype", separator = "", left_padding = 2 },
--           },
--         },
--         inactive_sections = {
--           lualine_a = { "filename" },
--           lualine_b = {},
--           lualine_c = {},
--           lualine_x = {},
--           lualine_y = {},
--           lualine_z = {},
--         },
--         tabline = {},
--         extensions = {},
--       }),
--     }
--   end,
-- }
return {}
